version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: MyApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reem231
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/MyApp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: reem231
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
